package backend.user;

public enum Neighborhoods {
    IFNMG,

    CIDADE_NOVA,
    CIDADE_VERDE,
    CIDADE_JARDIM,
    SAO_PEDRO,
    SANTO_ANTONIO,
    CENTRO,
    PLANALTO,
    RESIDENCIAL_LARANJEIRAS,
    PARQUE_SAO_JOAO,
    SAO_JUDAS_TADEU,
    DARWIN_CORDEIRO,
    TERESA_CRISTINA,
    JARDIM_PARAISO,
    MONTE_DAS_OLIVEIRAS,
    PEDRO_GOMES,
    SAO_FRANCISCO,
    PANORAMICO;
}
