import { Neighborhoods } from "@user/userTypes"; // ajuste o caminho
import type { Offer } from "./offerTypes";
import type { User } from "@user/userTypes"; // ajuste o caminho

const users: User[] = [
  {
    id: 1,
    name: "Pedro Inácio",
    email: "pedro@email.com",
    pictureUrl: "",
    phoneNumber: "(33) 99999-0001",
    address: Neighborhoods.CENTRO,
  },
  {
    id: 2,
    name: "Ana Clara",
    email: "ana@email.com",
    pictureUrl: "",
    phoneNumber: "(33) 99999-0002",
    address: Neighborhoods.CIDADE_NOVA,
  },
  {
    id: 3,
    name: "Carlos Silva",
    email: "carlos@email.com",
    pictureUrl: "https://i.pravatar.cc/150?u=carlos",
    phoneNumber: "(33) 99999-0003",
    address: Neighborhoods.SAO_PEDRO,
  },
  {
    id: 4,
    name: "Mariana Souza",
    email: "mariana@email.com",
    pictureUrl: "https://i.pravatar.cc/150?u=mariana",
    phoneNumber: "(33) 99999-0004",
    address: Neighborhoods.PLANALTO,
  },
  {
    id: 5,
    name: "João Pereira",
    email: "joao@email.com",
    pictureUrl: "https://i.pravatar.cc/150?u=joao",
    phoneNumber: "(33) 99999-0005",
    address: Neighborhoods.SANTO_ANTONIO,
  },
  {
    id: 6,
    name: "Beatriz Lima",
    email: "beatriz@email.com",
    pictureUrl: "https://i.pravatar.cc/150?u=beatriz",
    phoneNumber: "(33) 99999-0006",
    address: Neighborhoods.PANORAMICO,
  },
  {
    id: 7,
    name: "Rafael Costa",
    email: "rafael@email.com",
    pictureUrl: "https://i.pravatar.cc/150?u=rafael",
    phoneNumber: "(33) 99999-0007",
    address: Neighborhoods.SAO_FRANCISCO,
  },
];

const [pedro, ana, carlos, mariana, joao, beatriz, rafael] = users;

const vehicles = {
  onix: { id: 1, model: "Chevrolet Onix", color: "Prata", plate: "ABC-1234", capacity: 4 },
  gol: { id: 2, model: "Volkswagen Gol", color: "Branco", plate: "DEF-5678", capacity: 4 },
  biz: { id: 3, model: "Honda Biz", color: "Vermelha", plate: "", capacity: 1 },
  strada: { id: 4, model: "Fiat Strada", color: "Preta", plate: "GHI-9012", capacity: 3 },
};

export const mockOffers: Offer[] = [
  {
    id: 1,
    status: "Available",
    owner: pedro, // dono: você
    passengers: [ana],
    vehicle: vehicles.onix,
    capacity: 3,
    origin: Neighborhoods.CENTRO,
    destination: Neighborhoods.IFNMG,
    date: "10/12",
    departureTime: "06:45",
    description: "Saída pontual. Ar condicionado ligado.",
  },
  {
    id: 2,
    status: "Available",
    owner: carlos,
    passengers: [],
    vehicle: vehicles.gol,
    capacity: 3,
    origin: Neighborhoods.SAO_PEDRO,
    destination: Neighborhoods.IFNMG,
    date: "10/12",
    departureTime: "07:00",
    description:
      "Posso passar no Cidade Nova e no Santo Antônio se for no caminho. Aceito parada rápida para comprar pão.",
  },
  {
    id: 4,
    status: "Available",
    owner: joao,
    passengers: [],
    vehicle: vehicles.biz,
    capacity: 1,
    origin: Neighborhoods.SANTO_ANTONIO,
    destination: Neighborhoods.IFNMG,
    date: "11/12",
    departureTime: "07:15",
    description: "Moto, só uma vaga. Levo capacete extra.",
  },
  {
    id: 5,
    status: "Completed",
    owner: pedro,
    passengers: [ana, carlos],
    vehicle: vehicles.onix,
    capacity: 3,
    origin: Neighborhoods.IFNMG,
    destination: Neighborhoods.CENTRO,
    date: "09/12",
    departureTime: "17:30",
    description: "Volta para o centro depois das aulas.",
  },
  {
    id: 6,
    status: "Available",
    owner: ana,
    passengers: [pedro],
    vehicle: vehicles.gol,
    capacity: 3,
    origin: Neighborhoods.CIDADE_NOVA,
    destination: Neighborhoods.IFNMG,
    date: "12/12",
    departureTime: "06:50",
    description: "Saio da praça do bairro. Não tenho horário flexível, então peço pontualidade.",
  },
  {
    id: 7,
    status: "Available",
    owner: beatriz,
    passengers: [rafael],
    vehicle: vehicles.onix,
    capacity: 4,
    origin: Neighborhoods.PANORAMICO,
    destination: Neighborhoods.IFNMG,
    date: "12/12",
    departureTime: "07:30",
    description: "Sem descrição adicional.",
  },
  {
    id: 3,
    status: "Full",
    owner: mariana,
    passengers: [joao, beatriz, rafael],
    vehicle: vehicles.strada,
    capacity: 3,
    origin: Neighborhoods.PLANALTO,
    destination: Neighborhoods.IFNMG,
    date: "11/12",
    departureTime: "12:30",
    description: "Carona lotada, mas se alguém desistir eu reabro.",
  },
  {
    id: 8,
    status: "Full",
    owner: rafael,
    passengers: [mariana, joao],
    vehicle: vehicles.strada,
    capacity: 2,
    origin: Neighborhoods.SAO_FRANCISCO,
    destination: Neighborhoods.IFNMG,
    date: "13/12",
    departureTime: "18:00",
    description: "Noturno, saída depois da última aula.",
  },
];
